// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmyts_u-8WJGDUNPgz-nCS_v5ypC6FZeE',
    appId: '1:303170450929:web:9f84af56c43c9a0a988050',
    messagingSenderId: '303170450929',
    projectId: 'newproject-cbd71',
    authDomain: 'newproject-cbd71.firebaseapp.com',
    storageBucket: 'newproject-cbd71.firebasestorage.app',
    measurementId: 'G-MLJCTSCLH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD20lMtNG0GuoNUoXn6aVtLqTjazX--wFw',
    appId: '1:303170450929:android:48ae573b48457f8b988050',
    messagingSenderId: '303170450929',
    projectId: 'newproject-cbd71',
    storageBucket: 'newproject-cbd71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmwmF7_dQ2IB_LdBfiq7_mq4392-7adZs',
    appId: '1:303170450929:ios:e9ee35743ac27dd4988050',
    messagingSenderId: '303170450929',
    projectId: 'newproject-cbd71',
    storageBucket: 'newproject-cbd71.firebasestorage.app',
    iosBundleId: 'com.example.newf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmwmF7_dQ2IB_LdBfiq7_mq4392-7adZs',
    appId: '1:303170450929:ios:e9ee35743ac27dd4988050',
    messagingSenderId: '303170450929',
    projectId: 'newproject-cbd71',
    storageBucket: 'newproject-cbd71.firebasestorage.app',
    iosBundleId: 'com.example.newf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmyts_u-8WJGDUNPgz-nCS_v5ypC6FZeE',
    appId: '1:303170450929:web:2f83e155b061ec27988050',
    messagingSenderId: '303170450929',
    projectId: 'newproject-cbd71',
    authDomain: 'newproject-cbd71.firebaseapp.com',
    storageBucket: 'newproject-cbd71.firebasestorage.app',
    measurementId: 'G-7FQMMQ47N1',
  );
}
